pipeline {
    agent any
    environment
    {
        PATH = "/E/Maven/apache-maven-3.9.6/bin:$PATH"
    }
    stages {
        stage('Welcome') {
            steps {
                powershell 'ECHO WELCOME MASTER BRANCH'
            }
        }
        stage('Build') {
            steps {
                //powershell 'mvn -B -DskipTests clean package'
                powershell 'mvn clean deploy'
                sleep(20)
            }
        }
        stage('Test') {
            steps {
                // job to job
                //build job: 'boolParameter', parameters: [[$class: 'BooleanParameterValue', name: 'bool', value: true]]
                sleep(5)
                powershell 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('SonarQube-Analysis')
        {
            tools
            {
                def sonarHome = tool 'jenkins-sonar-scanner-tool'
            }
            steps
            {
                withSonarQubeEnv('sonarqube-server')
                {
                powershell "${sonarHome}/bin/sonar-scanner"
                }
            }
        }
        stage('Deliver') {
            steps {
                powershell './jenkins/scripts/deliver.sh'
            }
        }
    }
}
