pipeline {
    agent any
    stages {
        stage('Welcome') {
            steps {
                powershell 'ECHO WELCOME MASTER BRANCH'
            }
        }
        stage('Build') {
            steps {
                powershell 'mvn -B -DskipTests clean package'
                sleep(20)
            }
        }
        stage('Test') {
            steps {
                build'boolParameter'
                powershell 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                powershell './jenkins/scripts/deliver.sh'
            }
        }
    }
}
